sudo: required
dist: xenial
language: python

services:
  - docker

cache:
  directories:
    - cache

env:
  global:
    - MAJOR_VERSION=9
    - IMAGE_NAME=ccstudio$MAJOR_VERSION
    - BASE_IMAGE_NAME=ubuntu:19.04
    - URL=https://software-dl.ti.com/ccs/esd/CCSv9/CCS_9_2_0/exports/CCS9.2.0.00013_linux-x64.tar.gz
    - TARPATH=cache/ccs.tar.gz
    - TARNAME=ccs.tar.gz
# this version presently comes with what we want so...  comments it is
#    - INSTALL_IU=com.ti.cgt.c2000.18.linux.feature.group/18.12.3
#    - UNINSTALL_IU=com.ti.cgt.c2000.18.linux.feature.group/18.12.2

jobs:
  include:
    - stage: Build
      script:
      - if ! [ -f "$TARPATH" ]; then
          curl --location "$URL" > "$TARPATH";
        fi
      - ls -l "$TARPATH"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 60 docker build --pull --no-cache -t $IMAGE_NAME . --build-arg FROM="$BASE_IMAGE_NAME" --build-arg IU="$IU"
      - docker run --rm -it $IMAGE_NAME ccstudio -noSplash -data /workspace -application com.ti.ccstudio.apps.projectImport -ccs.help | grep -i usage
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
      - docker push $DOCKER_USERNAME/$IMAGE_NAME
