sudo: required

language: python

services:
  - docker

jobs:
  include:
    - stage: Build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 30 docker build -t ccstudio8 .
      - docker images
      - docker tag ccstudio8 $DOCKER_USERNAME/ccstudio8
      - docker images
    - stage: Deploy
      script:
      - docker images
      - docker push $DOCKER_USERNAME/ccstudio8
