sudo: required

language: python

services:
  - docker

jobs:
  include:
    - stage: Build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ccstudio8 .
      - docker images
      - docker tag ccstudio8 $DOCKER_USERNAME/ccstudio8
    - stage: Deploy
      script:
      - docker push $DOCKER_USERNAME/ccstudio8
