sudo: required
dist: xenial
language: python

services:
  - docker

cache:
  directories:
    - cache

env:
  global:
    - MAJOR_VERSION=8
    - IMAGE_NAME=ccstudio$MAJOR_VERSION
    - BASE_IMAGE_NAME=ubuntu:19.04
    - URL=http://software-dl.ti.com/ccs/esd/CCSv8/CCS_8_3_0/exports/CCS8.3.0.00009_linux-x64.tar.gz
    - TARPATH=cache/ccs.tar.gz
    - TARNAME=ccs.tar.gz
    - IU=com.ti.cgt.c2000.18.linux.feature.group/18.12.1

jobs:
  include:
    - stage: Build
      script:
      - if ! [ -f "$TARPATH" ]; then
          curl "$URL" > "$TARPATH";
        fi
      - ls -l "$TARPATH"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 30 docker build --pull --no-cache -t $IMAGE_NAME . --build-arg FROM="$BASE_IMAGE_NAME" --build-arg IU="$IU"
      - docker run --rm -it $IMAGE_NAME ccstudio -noSplash -data /workspace -application com.ti.ccstudio.apps.projectImport -ccs.help | grep -i usage
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME
      - docker push $DOCKER_USERNAME/$IMAGE_NAME
