sudo: required

language: python

services:
  - docker

cache:
  directories:
    - cache

env:
  global:
    - URL=http://downloads.ti.com/ccs/esd/CCSv8/CCS_8_0_0/exports/CCS8.0.0.00016_linux-x64.tar.gz
    - TARPATH=cache/ccs.tar.gz
    - TARNAME=ccs.tar.gz

jobs:
  include:
    - stage: Build
      script:
      - if ! [ -f "$TARPATH" ]; then
          curl "$URL" > "$TARPATH";
        fi
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - travis_wait 30 docker build -t ccstudio8 .
      - docker images
      - docker tag ccstudio8 $DOCKER_USERNAME/ccstudio8
      - docker images
      - docker push $DOCKER_USERNAME/ccstudio8
